### ISSUE TITLE
Connect hangs trying to get character list on Ruby 3.2.1 on Windows.

### ISSUE THREAD

**Issue by vtcifer** [elanthia-online/lich-5#290]
Fresh built environment Using Ruby 3.2.1 x64 

When filling in account name + password it just hangs at "working..."

Debug log shows the following (with data redacted):

```
2023-02-10 06:05:58: info: Lich 5.6.2
2023-02-10 06:05:58: info: Ruby 3.2.1
2023-02-10 06:05:58: info: x64-mingw-ucrt
2023-02-10 06:05:59: info: no force-mode info given
2023-02-10 06:06:07: error in Gtk.queue: undefined method `=~' for [{:game_code=>"DR", :game_name=>"DragonRealms", :char_code=>"<REDACTED>", :char_name=>"<REDACTED>"}, {:game_code=>"DRT", :game_name=>"DragonRealms Prime Test", :char_code=>"<REDACTED>", :char_name=>"<REDACTED>"}, {:game_code=>"GST", :game_name=>"GemStone IV Prime Test", :char_code=>"C", :char_name=>"0"}, {:game_code=>"GST", :game_name=>"GemStone IV Prime Test", :char_code=>"100", :char_name=>"0"}]:Array
	G:/My Drive/lichswarm/lib/gui-manual-login.rb:121:in `block (2 levels) in <top (required)>'
	G:/My Drive/lichswarm/lib/gtk.rb:101:in `block in queue'
	C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:686:in `invoke'
	C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:686:in `invoke'
	C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:112:in `main'
	G:/My Drive/lichswarm/lich.rbw:5209:in `<main>'
```

I'll try stepping back ruby versions (3.1, 3.0 etc), but installing and building gems on windows is a pain so it'll take me some time.

* edit: forgot to attach environ details (ruby / gem versions)
[environ-details.txt](https://github.com/elanthia-online/lich-5/files/10706733/environ-details.txt)

**Comment by MahtraDR** [comment]
Nice! I don't normally test windows stuff. 

I am mostly sure I know what the issue is. Can fix tomorrow.

**Comment by vtcifer** [comment]
Works with 3.1.3, environ details attached. 

[environ-details-3_1_3.txt](https://github.com/elanthia-online/lich-5/files/10707074/environ-details-3_1_3.txt)

**Comment by MahtraDR** [comment]
It's because login_info is an array, and ruby 3.2 has very strict comparisons. It's very late here, but if you can test changing line 121 in from
```ruby
if login_info =~ /error/i
```
to
```ruby
if login_info.to_s =~ /error/i
```

**Comment by vtcifer** [comment]
> It's because login_info is an array, and ruby 3.2 has very strict comparisons. It's very late here, but if you can test changing line 121 in from
> 
> ```ruby
> if login_info =~ /error/i
> ```
> 
> to
> 
> ```ruby
> if login_info.to_s =~ /error/i
> ```
> 
> That should solve it.

Will try to get that later today, thanks for the quick check.

**Comment by vtcifer** [comment]
> That should solve it.

Confirmed, fixed it.

**Comment by ondreian** [comment]
I think the larger issue here is the Lich is swallowing errors that should
bubble up to stderr.  It makes debugging/dev very hard.

**Comment by MahtraDR** [comment]
> I think the larger issue here is the Lich is swallowing errors that should
> bubble up to stderr.  It makes debugging/dev very hard.

I don't disagree, but that's a much larger issue too. It's a standard troubleshooting aspect to look at the logs in temp for us, which does mitigate much.
